# Generated by Django 4.2.22 on 2025-11-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=70, unique=True, verbose_name='Адрес места')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Широта')),
                ('lon', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Долгота')),
            ],
        ),
    ]
