# Generated by Django 4.2.22 on 2025-11-11 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата запроса к геокодеру'),
        ),
    ]
