# Generated by Django 4.2.26 on 2025-11-25 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=70, unique=True, verbose_name='Адрес места')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Широта')),
                ('lon', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Долгота')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата запроса к геокодеру')),
            ],
        ),
    ]
