# Generated by Django 4.2.22 on 2025-09-09 16:15


from django.db import migrations


def calculate_order_item_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    order_items = OrderItem.objects.all()
    for order_item in order_items:
        order_item.price = order_item.product.price
        order_item.save()


def move_backward(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    order_items = OrderItem.objects.all()
    for order_item in order_items:
        order_item.price = 0.00
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(calculate_order_item_price, move_backward)
    ]
