# Generated by Django 4.2.22 on 2025-10-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACTD', 'Принятый'), ('PRCD', 'В обработке'), ('DLVR', 'Доставляется'), ('DLRD', 'Выполнен')], db_index=True, default='ACTD', max_length=4),
        ),
    ]
