# Generated by Django 4.2.22 on 2025-10-07 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Звонок совершен'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Доставлен'),
        ),
        migrations.AddField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Принят'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(default='', verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACTD', 'Принятый'), ('PRCD', 'В обработке'), ('DLVR', 'Доставляется'), ('DLRD', 'Выполнен')], db_index=True, default='ACTD', max_length=4, verbose_name='Статус'),
        ),
    ]
