# Generated by Django 4.2.22 on 2025-10-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_way',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('ELCT', 'Безналично')], db_index=True, default='ELCT', max_length=4, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACTD', 'Принятый'), ('PRCD', 'Готовится'), ('DLVR', 'Доставляется'), ('DLRD', 'Выполнен')], db_index=True, default='ACTD', max_length=4, verbose_name='Статус'),
        ),
    ]
