# Generated by Django 4.2.22 on 2025-10-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_payment_way_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.CharField(blank=True, choices=[('1RES', 'Star Burger Арбат'), ('2RES', 'Star Burger Цветной')], db_index=True, max_length=4, verbose_name='Какой ресторан будет готовить'),
        ),
    ]
