# Generated by Django 4.2.22 on 2025-11-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Звонок совершен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_way',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('ELCT', 'Безналично')], db_index=True, max_length=4, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NPRC', 'Не обработан'), ('ACTD', 'Принят'), ('PRCD', 'Готовится'), ('DLVR', 'Доставляется'), ('DLRD', 'Выполнен')], db_index=True, default='NPRC', max_length=4, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='foodcartapp.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='foodcartapp.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Количество'),
        ),
    ]
