# Generated by Django 4.2.22 on 2025-11-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_called_at_alter_order_payment_way_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_way',
            field=models.CharField(blank=True, choices=[('CASH', 'Наличными'), ('ELCT', 'Безналично')], db_index=True, max_length=4, verbose_name='Способ оплаты'),
        ),
    ]
